### ISSUE TITLE
Real industrial use case

### ISSUE THREAD

**Issue by abylikhsanov** [cqylunlun/GLASS#10]
Hi,

Have you tried on actually applying this in a real world industrial defect detection?

**Comment by cqylunlun** [comment]
We have indeed completed the deployment of the Python solution within the project. However, the further implementation in real industrial scenarios is beyond the scope of this repository. This work primarily focuses on proposing a new method and dataset for anomaly detection from an academic perspective.

**Comment by abylikhsanov** [comment]
From your personal view, do you think this would work in real world industrial defect detection? Given lighting conditions are always stable

**Comment by cqylunlun** [comment]
For the real woven fabric defect detection in our project, the camera is located inside an enclosed case on the production line, ensuring that the shooting angle, lighting environment, and sample background remain consistent. If the same conditions can be ensured, you might consider trying this unsupervised anomaly detection solution.

**Comment by abylikhsanov** [comment]
Great, I will try it. Based on **MPDD** benchmark, it does mean that this model actually is orientation invariant given that it has been trained on all possbile sides of the object?

**Comment by cqylunlun** [comment]
Yes, the experimental results support this point. However, the differences between different surfaces in the samples of MPDD are limited. Your specific requirements still need further verification.
