### ISSUE TITLE
库中似乎没有给出main函数的具体实现？

### ISSUE THREAD

**Issue by ggfgtonyquan** [cqylunlun/GLASS#15]
可以提交完整的main函数吗

**Comment by cqylunlun** [comment]
本库中的代码文件是完整的，请参考[运行实验指导](https://github.com/cqylunlun/GLASS?tab=readme-ov-file#run-experiments)，通过执行shell文件调用`main.py`。根据传入的参数顺序，`main.py`的主函数会自动依次执行子命令[net](https://github.com/cqylunlun/GLASS/blob/29c2f664757951a47020c47f43fa88003a31955e/main.py#L27)、[dataset](https://github.com/cqylunlun/GLASS/blob/29c2f664757951a47020c47f43fa88003a31955e/main.py#L118)和[run](https://github.com/cqylunlun/GLASS/blob/29c2f664757951a47020c47f43fa88003a31955e/main.py#L252)。关于具体运行细节，您可以通过调试来进一步查阅。
