### ISSUE TITLE
为何运行该代码，srew类别性能不及论文中性能，仅有91.8？

### ISSUE THREAD

**Issue by GuoRunTang** [cqylunlun/GLASS#16]
为何运行该代码，srew类别性能不及论文中性能，仅有91.8？

**Comment by cqylunlun** [comment]
您好，我们已经进行了多次验证，Screw类别均未出现明显下降。除此以外，问题#13的提问者也给出了Screw类别上合理的实验结果。请您重新检查实验配置，并考虑以下几种可能的解决方案：
1. 参照 #3，下载Foreground Mask并将--fg设置为1 ；
2. 测试时按照代码，默认选择ckpt_best_*.pth ；
3. 确保程序运行完所有640个epoch ；
4. 检查数据集完整性。
