### ISSUE TITLE
请问详细的运行环境是什么？包括python click等版本

### ISSUE THREAD

**Issue by jimmyxzy** [cqylunlun/GLASS#17]
jimmy@jimmy-PR4908P-QD:/mnt/7.2T/AnomalyDetection/anomalib/GLASS-main/shell$ bas                        h run-mvtec.sh
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    @main.result_callback()
TypeError: 'NoneType' object is not callable

运行脚本 提示以上错误。谢谢您

**Comment by jimmyxzy** [comment]
https://github.com/DonaldRR/SimpleNet/issues/40     参考问题

**Comment by cqylunlun** [comment]
python=3.9.15
click==8.1.7
环境配置见[Environments](https://github.com/cqylunlun/GLASS?tab=readme-ov-file#environments)，具体模块版本见[requirements.txt](https://github.com/cqylunlun/GLASS/blob/main/requirements.txt).

**Comment by mrljwlm** [comment]
windows按照 pip install -r requirements.txt 安装的torch是cpu版本的啊，是不是要装gpu版本才对

**Comment by cqylunlun** [comment]
是的，需要gpu版本，cpu版需要将代码中的device设置为cpu。torch的gpu版本可以根据设备情况，在官网上选择合适的下载命令。
