### ISSUE TITLE
What does the augpath path hold?

### ISSUE THREAD

**Issue by genzhengmiaohong** [cqylunlun/GLASS#2]

**Comment by cqylunlun** [comment]
The argument `--augpath` holds the auxiliary texture dataset DTD, which is used for image-level data augmentation in GLASS. The download link for this public dataset is provided in the [Data Preparation](https://github.com/cqylunlun/GLASS#data-preparation) section.

**Comment by genzhengmiaohong** [comment]
Ok thanks, I will set augpath to the path of the dtd dataset.
