### ISSUE TITLE
Request for Access to Pre-trained Weights for GLASS and Alternative Execution Methods on Windows

### ISSUE THREAD

**Issue by yvonneku9986** [cqylunlun/GLASS#21]
Dear Qiyu Chen,
I hope this email finds you well. First, I would like to express my sincere gratitude for developing such an incredible technology—GLASS. I am particularly impressed by the high accuracy it demonstrates in detecting object defects. Your work has truly advanced the field, and I deeply admire the precision your technology offers in this critical area.

I am currently working on a research project at my university, where I am exploring defect detection techniques for objects as part of my studies in Information Engineering. GLASS has shown great potential for my research, and I would like to experiment further with it. To that end, I was wondering if you could kindly provide access to the pre-trained weights or any additional resources that would aid in the training process.

Additionally, we are planning to run experiments using the command bash run -dataset.sh. However, since we are running it on a Windows environment, I was wondering if there are alternative methods to execute this script on Windows besides installing a Linux virtual environment. Any guidance you could provide on this would be greatly appreciated.

Your help would be invaluable, and I am excited to explore the full potential of your innovative work in an academic context.

Thank you in advance for your time and consideration. I look forward to hearing from you.

Best regards,
Yvonne Ku

**Comment by cqylunlun** [comment]
1. Thank you for recognizing our work. To better assist the community and support future research, we plan to release the model weights for all categories of MVTec AD within two weeks.
2. For the deployment on Windows, you can refer to #19 and use the terminal to run the Python command.

**Comment by cqylunlun** [comment]
The model weights of GLASS are now provided in the [Data Preparation](https://github.com/cqylunlun/GLASS?tab=readme-ov-file#data-preparation) section.

**Comment by yvonneku9986** [comment]
thanks for your reply
