### ISSUE TITLE
ValueError: 'a' cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by William9Baker** [cqylunlun/GLASS#24]
When run this line 'aug = PIL.Image.open(np.random.choice(self.anomaly_source_paths)).convert("RGB")', I encountered this error. By the way,  how to debug in 'bash run-wfdd.sh' mode?

**Comment by William9Baker** [comment]
Maybe this image path was null, but I don't know why?

**Comment by cqylunlun** [comment]
1. Similar to #2 , please download the texture dataset DTD (Describable Textures Dataset), and configure `--augpath` with its absolute path.
2. Similar to #19 , you can use the command-line arguments to debug.

**Comment by William9Baker** [comment]
> 1. Similar to [What does the augpath path hold? #2](https://github.com/cqylunlun/GLASS/issues/2) , please download the texture dataset DTD (Describable Textures Dataset), and configure `--augpath` with its absolute path.
> 2. Similar to [Impossible to train custom datasets... #19](https://github.com/cqylunlun/GLASS/issues/19) , you can use the command-line arguments to debug.

Thanks, but how to debug the code with so many parameters?

**Comment by cqylunlun** [comment]
For example, in PyCharm, you can input the command-line arguments into the `Script Parameters` box for debugging.
![debug](https://github.com/user-attachments/assets/853684ae-5b54-4c39-aaf5-7de9dcd2f28f)
