### ISSUE TITLE
请问一下怎么在c++中部署

### ISSUE THREAD

**Issue by dabensongbing** [cqylunlun/GLASS#30]

**Comment by cqylunlun** [comment]
您好，本项目只包含pth模型转onnx，以及python ort推理代码，不包含c++部署部分。

**Comment by dabensongbing** [comment]
> python ort

希望大佬可以提供一个c++下openvino/tensorrt下部署的仓库（weak。。。

**Comment by dabensongbing** [comment]
> c++算法部署并非本人负责，抱歉短期内没有能力提供，如果有熟悉部署的伙伴欢迎PR。

非常感谢大佬

**Comment by soo-s** [comment]
导出onnx时存在的adapt_avg_pool无法export时的问题，请问您有解决吗。

**Comment by cqylunlun** [comment]
请参考 #41  ，下载最新的代码文件。
