### ISSUE TITLE
训练自己数据集

### ISSUE THREAD

**Issue by dabensongbing** [cqylunlun/GLASS#31]
请问大佬，我在训练自己数据集的时候，只有一个类，test里的内容和mvtec不太一样，应该修改哪些地方

**Comment by dabensongbing** [comment]
> 1. 确保数据集格式与MVTec AD格式保持一致;
> 2. shell文件第3行只需要填写一个类别的名称;
> 3. 如果没有test文件夹或没有ground truth，请参照[关于自定义数据集 #8](https://github.com/cqylunlun/GLASS/issues/8)修改代码。

我参考了您提供的方法做了如下修改，在mvtec.py中修改了get_image_data
    def get_image_data(self):
        imgpaths_per_class = {}
        maskpaths_per_class = None
        # maskpaths_per_class = {}

        classpath = os.path.join(self.source, self.classname, self.split.value)
        # maskpath = os.path.join(self.source, self.classname, "ground_truth")
        anomaly_types = os.listdir(classpath)

        imgpaths_per_class[self.classname] = {}
        # maskpaths_per_class[self.classname] = {}

        for anomaly in anomaly_types:
            anomaly_path = os.path.join(classpath, anomaly)
            anomaly_files = sorted(os.listdir(anomaly_path))
            imgpaths_per_class[self.classname][anomaly] = [os.path.join(anomaly_path, x) for x in anomaly_files]

            # if self.split == DatasetSplit.TEST and anomaly != "good":
            #     anomaly_mask_path = os.path.join(maskpath, anomaly)
            #     anomaly_mask_files = sorted(os.listdir(anomaly_mask_path))
            #     maskpaths_per_class[self.classname][anomaly] = [os.path.join(anomaly_mask_path, x) for x in anomaly_mask_files]
            # else:
            #     maskpaths_per_class[self.classname]["good"] = None

        data_to_iterate = []
        for classname in sorted(imgpaths_per_class.keys()):
            for anomaly in sorted(imgpaths_per_class[classname].keys()):
                for i, image_path in enumerate(imgpaths_per_class[classname][anomaly]):
                    data_tuple = [classname, anomaly, image_path]
                    # if self.split == DatasetSplit.TEST and anomaly != "good":
                    #     data_tuple.append(maskpaths_per_class[classname][anomaly][i])
                    # else:
                    #     data_tuple.append(None)
                    data_to_iterate.append(data_tuple)
        return imgpaths_per_class, data_to_iterate
        
    并且在glass.py中修改了
               。。。
                if (i_epoch + 1) % self.eval_epochs == 0:
                # 不计算roc等让训练时不需要test
                # images, scores, segmentations, labels_gt, masks_gt = self.predict(val_data)
                # image_auroc, image_ap, pixel_auroc, pixel_ap, pixel_pro = self._evaluate(images, scores, segmentations,
                #                                                                          labels_gt, masks_gt, name)
                #
                。。。
                #     torch.save(state_dict, ckpt_path_best)
                #     shutil.rmtree(eval_path, ignore_errors=True)
                #     shutil.copytree(train_path, eval_path)
                #
                # pbar_str1 = f" IAUC:{round(image_auroc * 100, 2)}({round(best_record[0] * 100, 2)})" \
                #             f" IAP:{round(image_ap * 100, 2)}({round(best_record[1] * 100, 2)})" \
                #             f" PAUC:{round(pixel_auroc * 100, 2)}({round(best_record[2] * 100, 2)})" \
                #             f" PAP:{round(pixel_ap * 100, 2)}({round(best_record[3] * 100, 2)})" \
                #             f" PRO:{round(pixel_pro * 100, 2)}({round(best_record[4] * 100, 2)})" \
                #             f" E:{i_epoch}({best_record[-1]})"
                pbar_str += pbar_str1
                pbar.set_description_str(pbar_str)

            torch.save(state_dict, ckpt_path_save)
        return best_record
        然后我创建了一个空的test文件夹与train文件夹同级，训练时
        Traceback (most recent call last):
  File "E:\project\deepproject\GLASS-main\main.py", line 351, in <module>
    main()
  File "D:\conda\envs\glass_env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\conda\envs\glass_env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\conda\envs\glass_env\lib\site-packages\click\core.py", line 1720, in invoke
    return _process_result(rv)
  File "D:\conda\envs\glass_env\lib\site-packages\click\core.py", line 1657, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "D:\conda\envs\glass_env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\project\deepproject\GLASS-main\main.py", line 268, in run
    list_of_dataloaders = methods["get_dataloaders"](seed, test)
  File "E:\project\deepproject\GLASS-main\main.py", line 175, in get_dataloaders
    test_dataset = dataset_library.__dict__[dataset_info[1]](
  File "E:\project\deepproject\GLASS-main\datasets\mvtec.py", line 118, in __init__
    0 * list(next(iter(self.imgpaths_per_class.values())).values())[0])
IndexError: list index out of range
似乎在读取dtd路径后出现了问题，麻烦大佬帮忙一下（磕头

**Comment by cqylunlun** [comment]
请下载[Google Drive](https://drive.google.com/file/d/1RjdbnsSt7C6DuoN__a8WHCrXOS_ebgSk/view?usp=sharing)链接下的.rar压缩包，其中包含 @SixGodGG 修改后训练和推断过程中无需gt和test文件夹的代码，您可以下载并替换对应文件进行调试（仅供参考）。

**Comment by dabensongbing** [comment]
> 请下载[Google Drive](https://drive.google.com/file/d/1RjdbnsSt7C6DuoN__a8WHCrXOS_ebgSk/view?usp=sharing)链接下的.rar压缩包，其中包含 @SixGodGG 修改后训练和推断过程中无需gt和test文件夹的代码，您可以下载并替换对应文件进行调试（仅供参考）。

谢谢大佬

**Comment by cqylunlun** [comment]
Thanks for your recognition. The link is still valid, and the file is a compressed package. Please download it directly.

**Comment by FitzFitzFitz** [comment]
<img width="496" height="243" alt="Image" src="https://github.com/user-attachments/assets/3272c6b2-1e6d-4c03-b45d-b8916e7e485d" />
sorry but this is what I got from this link

**Comment by cqylunlun** [comment]
<img width="2228" height="1145" alt="Image" src="https://github.com/user-attachments/assets/d9ef3f87-7aa6-42cf-a74b-11f57abe4fa9" />
you can download the .rar file through this button~
