### ISSUE TITLE
关于代码调试相关

### ISSUE THREAD

**Issue by dhyuk54** [cqylunlun/GLASS#33]
大佬,非常感谢您的分享,运行代码是没有任何问题的,但是有关参数都写在了.sh的脚本文件当中而不是通过add parser的方式传入到main 就算打了断点还是没有跳进去  所以就想知道调试的话应该如何做呢?

**Comment by cqylunlun** [comment]
感谢认可，请参考 #24 使用命令行参数调试。

**Comment by dhyuk54** [comment]
> 感谢认可，请参考 #24 使用命令行参数调试。

在pycharm 的 Script Parameter当中输入了以下命令之后可以用命令行的方式调试了 
非常感谢 
--gpu 0
--seed 0
--test ckpt
net
-b wideresnet50
-le layer2
-le layer3
--pretrain_embed_dimension 1536
--target_embed_dimension 1536
--patchsize 3
--meta_epochs 5
--eval_epochs 1
--dsc_layers 2
--dsc_hidden 1024
--pre_proj 1
--mining 1
--noise 0.015
--radius 0.75
--p 0.5
--step 20
--limit 392
dataset
--distribution 0
--mean 0.5
--std 0.1
--fg 1
--rand_aug 1
--batch_size 8
--resize 288
--imagesize 288
-d grey_cloth
-d grid_cloth
-d yellow_cloth
-d pink_flower
wfdd
G:\dataset\WFDD
G:\dataset\dtd\images
