### ISSUE TITLE
The feature aggregation of the model looks so strange, why not use convolution for feature adaptation?

### ISSUE THREAD

**Issue by AncientRemember** [cqylunlun/GLASS#34]

**Comment by cqylunlun** [comment]
1. The feature aggregation in GLASS is similar to [PatchCore](https://github.com/amazon-science/patchcore-inspection), aiming to increase the receptive field size and improve robustness to small spatial deviations.
2. GLASS adopts a single-layer linear feature adapter to ensure simplicity and efficiency. Experimental results in [SimpleNet](https://github.com/DonaldRR/SimpleNet) show that fully connected layer outperforms convolutional layer. In addition, this is a common paradigm in AD methods.

**Comment by AncientRemember** [comment]
Thank you for your answers and I will follow up simplenet papaer's explanation in further detail

**Comment by AncientRemember** [comment]
In the Simplenet paper, there is no detailed explanation of why adaptive_avg_pool1d was used instead of adaptive_avg_pool2d

**Comment by cqylunlun** [comment]
In this step, channel and spatial information only interact within 3x3 neighborhood vectors, which corresponds to the "Locally Aware Patch Features" introduced in PatchCore. This process can be described as: [512 x 3 x 3 / 1024 x 3 x 3] -> [1536 / 1536] -> [1536]. Further debugging is recommended.

For more details on this issue, please refer to Section 3.1 of the [PatchCore paper](https://arxiv.org/pdf/2106.08265). The feature aggregation designs in both GLASS and SimpleNet are based on this concept. I previously mentioned that specific experiments in SimpleNet explain why a learnable linear feature adapter is used.

**Comment by AncientRemember** [comment]
path core use a adaptive_avg_pool2d to pool target layer's feature then concat, it's not equle to simaplenet

**Comment by cqylunlun** [comment]
1. The [official implementation of PatchCore](https://github.com/amazon-science/patchcore-inspection/blob/fcaa92f124fb1ad74a7acf56726decd4b27cbcad/src/patchcore/common.py#L170) also uses `adaptive_avg_pool1d` for feature aggregation. This process can be described as: [512 x 3 x 3 / 1024 x 3 x 3] -> [1024 / 1024] -> [1024]. SimpleNet only replaces the output channel dimension from 1024 to 1536.
2. Yes, the SimpleNet linear layer is similar to a 1x1 convolution.

**Comment by AncientRemember** [comment]
Thank you very much for your patience.

I was wondering if I could use pool2d+concat to simplify the calculations flow
So in the end, what do you suggest about the above question?

**Comment by cqylunlun** [comment]
This is a question worth investigating. I have tried replacing the above 1D step with 2D average pooling, but it results in a performance drop under the GLASS framework. You can replace the following code with [L153-L184](https://github.com/cqylunlun/GLASS/blob/8a52006aeef04a440778a5bbe978dfa6db26fb6a/glass.py#L153-L184) in `glass.py` to further explore the feasibility of 1D/2D feature aggregation.

```
  sample = None
  for feature in features:
      feature = F.avg_pool2d(feature, 3, 1, 1)
      sample = feature if sample is None else torch.cat(
          (sample, F.interpolate(feature, sample.shape[-2:], mode='bilinear', align_corners=False)), dim=1)
  sample = sample.permute(0, 2, 3, 1)
  patch_features = sample.reshape(-1, sample.shape[-1])
  patch_shapes = [list(x.shape[-2:]) for x in features]
```

**Comment by AncientRemember** [comment]
Indeed - the pooling operation aims to aggregate the local neighbourhood surrounding each featuremap location. Conceptually, this is done using the `PatchMaker`-class 
https://github.com/amazon-research/patchcore-inspection/blob/b64be4734cb8295bfbadccf4f6a036b266181e57/src/patchcore/patchcore.py#L277-L308
and the `MeanMapper`
https://github.com/amazon-research/patchcore-inspection/blob/b64be4734cb8295bfbadccf4f6a036b266181e57/src/patchcore/common.py#L163-L170

The `PatchMaker` unfolds an input image batch `[bs x c x h x w]` into a patchified version `[bs x h//stride * w//stride x c x patchsize x patchsize]`. This is done for each featuremap that you extract from a given backbone network. 
The patchified featuremaps are then rescaled to match the highest available featuremap resolution, and then each patch is averaged using the `MeanMapper` class, which is our local neighbourhood aggregation.
Note that in this particular case, an adaptive average pooling could have also done the trick, but the patchified approach can allow for other methods of aggregation (although we did end up just opting for the simple averaging).

Everything I have mentioned happens here:
https://github.com/amazon-research/patchcore-inspection/blob/b64be4734cb8295bfbadccf4f6a036b266181e57/src/patchcore/patchcore.py#L105-L141

in patchcore offical repository ,One issue is described in detail, but also does not address the benefits of adaptive_avg_pool1d
-------
Finally, just to highlight: the `Aggregator`-class
https://github.com/amazon-research/patchcore-inspection/blob/b64be4734cb8295bfbadccf4f6a036b266181e57/src/patchcore/common.py#L173-L183
also has an `adaptive_pooling` operation, but in this case only to bring the dimensionality of each utilized featuremap to a fixed `target_embed_dimension` - see also https://github.com/amazon-research/patchcore-inspection/issues/4#issuecomment-1123763551 for a more detailed explanation :).

_Originally posted by @Confusezius in https://github.com/amazon-science/patchcore-inspection/issues/7#issuecomment-1124857894_
