### ISSUE TITLE
What is "len(...) == 2" check after pre_projection?

### ISSUE THREAD

**Issue by SachihiroNakagawa** [cqylunlun/GLASS#35]
There are several places where the length is checked to see if it is 2 after pre_projection. What is the purpose of this processing?
In most cases, pre_projection returns much more than 2.
And if this processing is done, the number of dimensions will be reduced by one, causing an error.

e.g. glass.py line 588
patch_features = self.pre_projection(patch_features)
patch_features = patch_features[0] if len(patch_features) == 2 else patch_features

**Comment by cqylunlun** [comment]
This step is intended to facilitate the selection of single-layer outputs during debugging, but it is not meaningful in the current complete version.

**Comment by SachihiroNakagawa** [comment]
Thank you for the quick response.
I understand now!
