### ISSUE TITLE
How to use resnet18 as the backbone?

### ISSUE THREAD

**Issue by xrli-U** [cqylunlun/GLASS#37]
Hello, I want to use resnet18 as the backbone. To achieve the results of Table 5 in your paper,  what parts do I need to modify in the code? Or if you can provide the checkpoints under resnet18, I would be very grateful!

**Comment by cqylunlun** [comment]
Using ResNet-18 as an example, if you want to use `layer1+layer2+layer3`, you can modify [L12~L14](https://github.com/cqylunlun/GLASS/blob/af45306c72513409a72bb820d796e15d4b83e083/shell/run-mvtec.sh#L12-L14) in `run-mvtec.sh` as follows:
```
    -b resnet18 \
    -le layer1 \
    -le layer2 \
    -le layer3 \
```

**Comment by cqylunlun** [comment]
That's right. To achieve the result of resnet18 in Table 5, you only need to modify [L12](https://github.com/cqylunlun/GLASS/blob/af45306c72513409a72bb820d796e15d4b83e083/shell/run-mvtec.sh#L12) to:
```
    -b resnet18 \
```
