### ISSUE TITLE
请教关于推理的问题

### ISSUE THREAD

**Issue by dellinehex7** [cqylunlun/GLASS#39]
作者您好。感谢您分享的非常有意义的工作。
我们发现您的开源项目中未提供checkpoint，由于我们的研究主要专注于图像的前后处理算法，我们希望能够直接使用GLASS的checkpoint对我们前处理的图像直接进行推理。
如果作者方便提供相关的checkpoint，我们将不胜感激。

**Comment by cqylunlun** [comment]
感谢认可。请参考问题 #20 ，GLASS的checkpoint已在 [Data Preparation](https://github.com/cqylunlun/GLASS?tab=readme-ov-file#data-preparation) 部分提供。

**Comment by dellinehex7** [comment]
您好，很感谢您提供了MVTec AD数据集的checkpint。请问作者可以提供VisA，MPDD等数据集的相关checkpoint吗？我们希望能够针对不同数据集对我们的算法进行改进。非常感谢。

**Comment by cqylunlun** [comment]
由于时间有限和工作安排，本项目只针对MVTec AD给出checkpoint示例。目前没有计划整理其他数据集的模型，您可以根据代码训练得到这些模型。

**Comment by dellinehex7** [comment]
好的，非常感谢您的回复！

**Comment by soo-s** [comment]
您好，请问能够分享推理pth文件的代码吗？我基于onnx的代码修改了pth的推理代码，但是似乎输入格式不正确导致了输出特征图不是预期。

**Comment by cqylunlun** [comment]
请参考 #41  ，下载最新的代码文件。
