### ISSUE TITLE
Distribution: 0 /Maniflod

### ISSUE THREAD

**Issue by crazyblueer** [cqylunlun/GLASS#6]
When I run the model, the console printed this line out and then finished the program quickly. What does this mean and how can I fix the error? Thank you sm for answering! 

"INFO:__main__:Dataset       tomatoes  : train=404 test=67
INFO:__main__:Selecting dataset [mvtec_tomatoes] (1/1) 2024-07-26 15:47:22

Distribution: 0 / Maniflod."

**Comment by cqylunlun** [comment]
The above step involves the 'Image-level Spectrogram Analysis' described in the paper, aiming to determine the distribution for different categories as either 'Manifold' and 'Hypersphere', which corresponds to GLASS variant between 'GLASS-m' and 'GLASS-h':

1. For the datasets mentioned in the paper, we have already completed the 'Image-level Spectrogram Analysis' and stored the results in an Excel file located at `./datasets/excel/*_distribution.xlsx`.
2. For datasets not mentioned in the paper, GLASS first needs to perform 'Image-level Spectrogram Analysis'. Based on your console output, the first run of `run-dataset.sh` determines that the "tomatoes" category follows a 'Manifold' distribution, and a new Excel file has been generated at `./datasets/excel/mvtec_distribution.xlsx`. Then, running `run-dataset.sh` again will allow you to start training using the 'GLASS-m'.

Additionally, you can directly select the GLASS variant by modifying the argument `--distribution` in `run-dataset.sh`:

1. When `distribution=0`, it reads the distribution type stored in the local Excel file. If the file is not found, it would perform a new 'Image-level Spectrogram Analysis' (as in your case).
2. When `distribution=1`, it ignores the local Excel file and performs a new 'Image-level Spectrogram Analysis'.
3. When `distribution=2`, it directly selects the 'GLASS-m' based on the 'Manifold' distribution.
4. When `distribution=3`, it directly selects the 'GLASS-h' based on the 'Hypersphere' distribution.

For more details, please see lines [L205~L227](https://github.com/cqylunlun/GLASS/blob/23e2e2cefc975de35b57e2a9e59e388fb8977fda/glass.py#L205) in `glass.py`.

**Comment by crazyblueer** [comment]
@cqylunlun Thank you very much for the detailed explanation! I have one more question regarding to running with custom dataset, I organized my dataset to match with the structure of mvtec dataset. Then I made a copy of the "run-mvtec.sh" to my dataset "run-dataset.sh". My question is: In the main.py and datasets/mvtec.py , do I have to also modify the mvtec dataset to the name of my dataset? Sorry to ask such a mundane question, I am quite inexperienced in it and trying to figure out how to run the model.

**Comment by cqylunlun** [comment]
For running with a custom dataset which matches the structure of MVTec AD, you don't need to modify any code to start training normally. However, you can make the following modifications to ensure that all results (excels, models, and visualizations) will have the prefix changed from 'mvtec' to 'your_dataset_name':
1. Add the key-value pair `"your_dataset_name": ["datasets.mvtec", "MVTecDataset"]` to `_DATASETS` at [L167~L168](https://github.com/cqylunlun/GLASS/blob/23e2e2cefc975de35b57e2a9e59e388fb8977fda/main.py#L167) in `main.py`.
2. Replace 'mvtec' with 'your_dataset_name' in the [last line](https://github.com/cqylunlun/GLASS/blob/23e2e2cefc975de35b57e2a9e59e388fb8977fda/shell/run-mvtec.sh#L37) of `run-dataset.sh`.

If you have any more questions or run into issues, feel free to ask!

**Comment by crazyblueer** [comment]
@cqylunlun  Thank you very much! I have modified as suggested but then I encountered this error:  "a" cannot be empty unless no samples are taken, even though I am pretty sure that I have config my paths for datapath and augpath correctly. Do I have to also dowload the dataset of mvtec as well beside dtd? 

"Traceback (most recent call last):
  File "C:\Users\A\Downloads\GLASS-main\main.py", line 352, in <module>
    main()
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1720, in invoke
    return _process_result(rv)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\Downloads\GLASS-main\main.py", line 299, in run
    flag = GLASS.trainer(dataloaders["training"], dataloaders["testing"], dataset_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\Downloads\GLASS-main\glass.py", line 233, in trainer
    for i, data in enumerate(training_data):
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_utils.py", line 705, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "C:\Users\A\Downloads\GLASS-main\datasets\mvtec.py", line 169, in __getitem__
    aug = PIL.Image.open(np.random.choice(self.anomaly_source_paths)).convert("RGB")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy\\random\\mtrand.pyx", line 951, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken"
----------------------------------------------
 Here is my *.sh file:
datapath=/c/Users/A/Downloads/GLASS-main/tomatoes
augpath=/c/Users/A/Downloads/GLASS-main/dataset/dtd/images
classes=('red_tomatoes')
flags=($(for class in "${classes[@]}"; do echo '-d '"${class}"; done))

cd ..
python main.py \
    --gpu 0 \
    --seed 0 \
    --test ckpt \
  net \
    -b wideresnet50 \
    -le layer2 \
    -le layer3 \
    --pretrain_embed_dimension 1536 \
    --target_embed_dimension 1536 \
    --patchsize 3 \
    --meta_epochs 640 \
    --eval_epochs 1 \
    --dsc_layers 2 \
    --dsc_hidden 1024 \
    --pre_proj 1 \
    --mining 1 \
    --noise 0.015 \
    --radius 0.75 \
    --p 0.5 \
    --step 20 \
    --limit 392 \
  dataset \
    --distribution 0 \
    --mean 0.5 \
    --std 0.1 \
    --fg 0 \
    --rand_aug 1 \
    --batch_size 8 \
    --resize 288 \
    --imagesize 288 "${flags[@]}" tomatoes $datapath $augpath

**Comment by crazyblueer** [comment]
@cqylunlun Thank you so much for answering my question. My training is still on going with epoch 530 and it has been running for more than 2 days. Is that normal training time for this model? My second question is I notice within one epoch, the loss value fluctuates between samples, sometimes it gets to 8.28e-02 to 9.28e-02 then down to 3.e to 2.e to 1.e, it is not really decreasing linearly. How can I evaluate the learning of the model given this fluctuation in loss' values? I am afraid my loss function is not calculated well since I handcrafted my ground truth images, and the masks are mostly a bit bigger than the actual defects. Would it have any serious effect on the learning of the model? Are the ground truth images need to be perfect? Thank you so much once again!

**Comment by cqylunlun** [comment]
1. When training a category with 280 images, GLASS takes 4 hours to complete 640 epochs on an NVIDIA Tesla A800.
2. Due to the use of adversarial learning in GLASS, there may occasionally be fluctuations. However, the loss will converge again based on experience.
3. GLASS is an unsupervised anomaly detection method in which the defect images and labels in the test set are not exposed to the model during training.

**Comment by crazyblueer** [comment]
@cqylunlun thank u!! I just got the test result and it came out very good. Thank u for the great model! I have one more question regarding to improving the accuracy of the model. Since some defects on the heatmap were less bright,they look just plae blue right now.  How can I adjust the threshold so that the result will also record them? if I adjust the threshold, will I have to retrain the model? Second question is, if I have more "good" images in the future, should I keep training the model with new images so that it will improve its accuracy?

**Comment by cqylunlun** [comment]
1. Instead of retraining, you can modify the visualization code in glass.py, as detailed in issue [#3](https://github.com/cqylunlun/GLASS/issues/3#issuecomment-2246751612).
2. Although we have not verified the online learning capability of GLASS, you can try using the saved trained model and optimizer to continuously learn from new normal samples.

**Comment by crazyblueer** [comment]
@cqylunlun sorry to spam you with more question!! I see that in the training, the image size is resized to 288x288, and the result images after inference are also 288x288. However, my original images are around ~980x487. Therefore the output kinda cut away some parts of the images. Is there any way I can adjust the visualization so that the result will output the entire image? Or do I have to set the image size in the .sh file? Thank you for answering so many questions of mine

**Comment by cqylunlun** [comment]
No problem at all! I'm happy to help with your questions.

1. There is no need to modify the .sh file. First, change L113/L129/L150 in `mvtec.py` to ‘transforms.Resize([self.resize, self.resize])’. Second, comment out L122/L130/L154 in `mvtec.py`. Finally, modify L540 in `glass.py` to the target size ‘(980 * 3, 487)’. For better results, please retrain after making these changes.
2. In issue #8, we provided a training strategy that does not require ground truth images. For the testing strategy, please follow steps 1 and 2 to modify the [maskpath](https://github.com/cqylunlun/GLASS/blob/29c2f664757951a47020c47f43fa88003a31955e/datasets/mvtec.py#L230) in `mvtec.py` and the [tester](https://github.com/cqylunlun/GLASS/blob/29c2f664757951a47020c47f43fa88003a31955e/glass.py#L473) in `glass.py`.

_”Note that these steps cover only the key changes and may introduce some bugs, so your further debugging will be necessary.”_
