### ISSUE TITLE
About Custom dataset

### ISSUE THREAD

**Issue by wragon** [cqylunlun/GLASS#8]
If my custom dataset doesn’t have ground truth data and therefore no mask_path, how do I train?

**Comment by cqylunlun** [comment]
We follows the general paradigm of anomaly detection methods. Here is a feasible solution for practical application:

1. Modify [mvtec.py](https://github.com/cqylunlun/GLASS/blob/main/datasets/mvtec.py) to set `maskpaths_per_class` to `None`.
2. Comment out the code for metric calculation and model selection in [glass.py](https://github.com/cqylunlun/GLASS/blob/main/glass.py).
3. Select the model from the current or final epoch.

**Comment by lekklev** [comment]
@cqylunlun how will leaving out the ground truth masks influence the performance of the model? Has this been experimented?

**Comment by cqylunlun** [comment]
There hasn’t been any feedback yet—you can try it yourself by referring to issue #46. @SixGodGG has provided updated training and inference scripts that remove the dependency on the `ground_truth` and `test` folders. Download the `.rar` archive from [Google Drive](https://drive.google.com/file/d/1RjdbnsSt7C6DuoN__a8WHCrXOS_ebgSk/view?usp=sharing) and replace the corresponding files (for reference only).
